global using System.Net;
global using System.Text.Json;
global using Adnc.Infra.Core.Guard;
global using Consul;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
