global using Adnc.Infra.Entities;
global using Adnc.Infra.IRepositories;
global using Adnc.Infra.Repository.EfCore.Internal;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Storage;
global using System.Data;
global using System.Linq.Expressions;
global using Z.EntityFramework.Plus;