global using Adnc.Infra.Entities;
global using Adnc.Infra.Entities.Config;
global using Adnc.Infra.Repository;
global using Adnc.Shared.Consts.Entity.Maint;
global using Autofac;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System;
global using System.Collections.Generic;
global using System.Reflection;