global using Adnc.Infra.Entities;
global using Adnc.Demo.Maint.Repository.Entities;
global using Adnc.Shared;
global using Adnc.Demo.Shared.Const.Entity.Maint;
global using Adnc.Shared.Repository.EfEntities;
global using Adnc.Shared.Repository.EfEntities.Config;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
