version: '3.1'
services:
  mysql:
    image: mariadb:latest
    container_name: "andc-mariadb"
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "alpha.netcore"
      MYSQL_ROOT_PASSWORD: "alpha.netcore"
      TZ: "Asia/Shanghai"
    ports:
      - "13308:3306"
    volumes:
      - ../andc/mysql/data:/var/lib/mysql
      - ../andc/mysql/log:/var/log/mysql
