global using Adnc.Demo.Shared.Const.Entity.Usr;
global using Adnc.Demo.Usr.Repository.Entities;
global using Adnc.Infra.Repository;
global using Adnc.Infra.Repository;
global using Adnc.Infra.Repository.EfCore;
global using Adnc.Shared.Repository.EfEntities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
