global using Adnc.UnitTest.Fixtures;
global using DotNetCore.CAP;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Linq.Expressions;
global using System.Reflection;
global using Xunit;
global using Xunit.Abstractions;
