version: "3.6"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "9000:9000"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /mnt/user/appdata/portainer-ce:/data:rw
