using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace Adnc.Infra.Repository.EfCore.MongoDB;

/// <summary>
/// An entity in a MongoDB repository.
/// </summary>
public abstract class MongoEntity : IEntity<string>
{
    /// <summary>
    /// Gets or sets the identifier.
    /// </summary>
    //_id is generated by StringObjectIdGenerator and stored as string
    //[BsonId(IdGenerator = typeof(StringObjectIdGenerator))]
    // Tell MongoDB that this field is of type ObjectId in the database.
    // This attribute is added to ensure NLog stores it as ObjectId type.
    [BsonId(IdGenerator = typeof(StringObjectIdGenerator))]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = string.Empty;
}
