version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: adnc-mongodb
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: logs_dev
      MONGO_USERNAME: alpha
      MONGO_PASSWORD: football
    restart: always
    volumes:
        - ../adnc/mongo/data:/data/db
        - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 13017:27017
    cpus: 2
    mem_reservation: "400M"
    mem_limit: "500M"
    command:
        - mongod
        - --wiredTigerCacheSizeGB=0.5
        - --auth
    # network_mode: host
    # networks:
    #   kafka_net:
    #     ipv4_address: 172.27.10.2